/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-12-19 06:53:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views._2_005fbak;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class findEmailForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/dstay_workspace1/dstayproject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1576665400215L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"Kimi is a curated foods and beverages artisans.\">\r\n");
      out.write("    <meta name=\"author\" content=\"Johnson Chandra, Allysa Prabandani, Philipus Herlambang, Maya Editorial\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("    <meta name=\"mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"twitter:card\" content=\"summary\">\r\n");
      out.write("    <meta name=\"title\" content=\"Back to Kimi\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"Content-Language\" content=\"en-id\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- open graph metadata facebook, slack, whatsapp line -->\r\n");
      out.write("    <meta property=\"fb:app_id\" content=\"150112802189143\"/>\r\n");
      out.write("    <meta property=\"og:locale\" content=\"en_US\" />\r\n");
      out.write("    <meta property=\"og:title\" content=\"Back to Kimi\" />\r\n");
      out.write("    <meta property='og:site_name' content='Kimi | Curated Foods and Beverages' />\r\n");
      out.write("    <meta property=\"og:url\" content=\"http://kimistatic.s3-website-ap-southeast-1.amazonaws.com/\" />\r\n");
      out.write("    <meta property=\"og:description\" content=\"Kimi is a curated foods and beverages artisans.\" />\r\n");
      out.write("    <meta property='og:image' content=\"https://s3-ap-southeast-1.amazonaws.com/kimistatic/images/apple-touch-icon.png\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- open graph metadata twitter -->\r\n");
      out.write("    <meta name=\"twitter:title\" content=\"Back to Kimi\">\r\n");
      out.write("    <meta name=\"twitter:url\" content=\"http://www.backtokimi.com\">\r\n");
      out.write("    <meta name=\"twitter:description\" content=\"Kimi is a curated foods and beverages artisans.\">\r\n");
      out.write("    <meta name=\"twitter:image\" content=\"https://s3-ap-southeast-1.amazonaws.com/kimistatic/images/apple-touch-icon.png\">\r\n");
      out.write("    <meta name=\"twitter:site\" content=\"@backtokimi\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" href=\"https://s3-ap-southeast-1.amazonaws.com/kimistatic/images/favicon.ico\">\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"resources/css/2_bak/bootstrap.min.css?after\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"resources/css/2_bak/kimi.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"resources/css/2_bak/font-awesome.min.css?after\" rel=\"stylesheet\">\r\n");
      out.write("\t<title>findEmail</title>\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"http://ricostacruz.com/jquery.transit/jquery.transit.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Boot Strap -->\r\n");
      out.write("    <link href=\"resources/css/2_bak/bootstrap.min.css?after\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template css-->\r\n");
      out.write("    <link href=\"resources/css/2_bak/kimi.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom css -->\r\n");
      out.write("    <link href=\"resources/css/2_bak/logo-top.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"resources/css/2_bak/top-menu.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"resources/css/2_bak/mainBanner.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom JavaScript-->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"resources/js/2_bak/mobile-menu.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"resources/js/2_bak/mainBanner.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../1_common/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"kimi-container\">\r\n");
      out.write("        <!--breadcrumb start-->\r\n");
      out.write("        <ol class=\"breadcrumb hidden-xs\">\r\n");
      out.write("            <li><a href=\"home.do\">Home</a></li>\r\n");
      out.write("            <li class=\"active\">이메일아이디찾기</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("        <div class=\"clearfix\"></div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4 col-md-offset-4\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"box-bg-white col-md-12 col-xs-12 form-medium-padding\">\r\n");
      out.write("                        <h3 class=\"text-center text-gray-1\">이메일아이디 찾기</h3>\r\n");
      out.write("                        <p class=\"text-center\">회원정보에 등록한 휴대전화를 입력</p>\r\n");
      out.write("                        <div class=\"clearfix maya-small-padding\"></div>\r\n");
      out.write("\r\n");
      out.write("                        <form id=\"ajaxFindEmailForm\" action=\"\" method=\"post\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"tel\" class=\"form-control\" id=\"account_number\" placeholder=\"휴대폰 번호\" required name=\"phone\">\r\n");
      out.write("                            </div> \r\n");
      out.write("\r\n");
      out.write("                            <button type=\"button\" onclick=\"sendSMS()\" class=\"btn btn-outline-primary\">인증받기</button>\r\n");
      out.write("                            <div class=\"clearfix maya-tiny-padding\"></div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"bank_account_name\" placeholder=\"인증번호 6자리 숫자입력\" disabled>\r\n");
      out.write("                            </div> \r\n");
      out.write("                            <button type=\"button\" onclick=\"compareSMS()\" class=\"btn btn-block button-green-free btn-lg\">확인</button>\r\n");
      out.write("                            <input type=\"hidden\" id=\"hiddenEmail\">\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <div class=\"clearfix maya-tiny-padding\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("<form id=\"findEmailForm\" action=\"loginForm.do\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"findEmail\">\r\n");
      out.write("</form>           \r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div><!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("<!--include footer-->\r\n");
      out.write("<div class=\"include-footer\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core JavaScript\r\n");
      out.write("================================================== -->\r\n");
      out.write("<!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("<script src=\"resources/2_bak/js/jquery.min.js\"></script>\r\n");
      out.write("<script>window.jQuery || document.write('<script src=\"../../assets/js/vendor/jquery.min.js\"><\\/script>')</script>\r\n");
      out.write("<script src=\"resources/2_bak/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--kimi basic js-->\r\n");
      out.write("<script src=\"resources/2_bak/js/kimi.js\"></script>\r\n");
      out.write("<!--tooltip  -->\r\n");
      out.write("<script>\r\n");
      out.write("$(function () {\r\n");
      out.write("\t  $('[data-toggle=\"tooltip\"]').tooltip()\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\tvar randomSMS;\r\n");
      out.write("\t\tvar infoMem;\r\n");
      out.write("\t\tfunction sendSMS() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"ajaxfindEmail.do\",\r\n");
      out.write("\t\t\tmethod:\"post\",\r\n");
      out.write("\t\t\tdata:{phone:$(\"#account_number\").val()},\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\terror:function() {\r\n");
      out.write("\t\t\t\talert(\"등록되지 않은 휴대폰번호입니다\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess:function(infoMap) {\r\n");
      out.write("\t\t\t\tif( infoMap != null) {\r\n");
      out.write("\t\t\t\t\talert(\"인증번호가 발송되었습니다\");\r\n");
      out.write("\t\t\t\t\trandomSMS = infoMap.SMS;\r\n");
      out.write("\t\t\t\t\tinfoMem = infoMap.mem;\r\n");
      out.write("\t\t\t\t\t$(\"#bank_account_name\").attr(\"disabled\", false);\r\n");
      out.write("\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\talert(\"휴대폰 번호를 잘 입력해 주세요\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\tfunction compareSMS() {\r\n");
      out.write("\t\t\tif($(\"#bank_account_name\").val() == randomSMS) {\r\n");
      out.write("\t\t\t\talert(\"귀하의 이메일은 \" + infoMem + \" 입니다\");\r\n");
      out.write("\t\t\t\t$(\"input[name=findEmail]\").val(infoMem);\r\n");
      out.write("\t\t\t\t$(\"#findEmailForm\").submit();\r\n");
      out.write("\t\t\t}else if($(\"#bank_account_name\").val() == \"\"){\r\n");
      out.write("\t\t\t\talert(\"휴대폰 번호를 입력해 주세요\");\r\n");
      out.write("\t\t\t}else {\r\n");
      out.write("\t\t\t\talert(\"인증번호가 다릅니다\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
