/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-12-19 07:31:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views._3_005fhan;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class suggestionInsertForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/dstay_workspace1/dstayproject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1576665400215L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>DSTAY - 제안하기</title>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/ckeditor/ckeditor.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom css -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/4_jong/top-menu.css?ver=1\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/4_jong/mainBanner.css?ver=4\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/4_jong/specialCategory.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- 한도빈 Custom css -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/3_han/customer-center-main.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/3_han/frequency-question.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/3_han/suggestion-theme.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    \t#suggest_confirm_layer{\r\n");
      out.write("    \t\tbackground:white;\r\n");
      out.write("    \t\tdisplay:float;\r\n");
      out.write("    \t\tz-index:1000;\r\n");
      out.write("    \t\tposition:absolute;\r\n");
      out.write("    \t\twidth:400px;\r\n");
      out.write("    \t\tpadding:10px;\r\n");
      out.write("    \t\ttop:300px;\r\n");
      out.write("    \t\tleft:300px;\r\n");
      out.write("    \t\tborder:1px solid lightgray;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t#outBtn{\r\n");
      out.write("    \t\tcolor:orange;\r\n");
      out.write("    \t\tborder-color:orange;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t#okBtn{\r\n");
      out.write("    \t\tcolor:white;\r\n");
      out.write("    \t\tbackground-color:orange;\r\n");
      out.write("    \t\tborder-color:orange;\r\n");
      out.write("    \t}\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../1_common/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container-fluid\" id=\"suggestion-area\" style=\"padding-bottom: 50px; padding-top: 20px;\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-2\">\r\n");
      out.write("                <ul class=\"nav nav-pills nav-stacked left-side-nav-stacked\">\r\n");
      out.write("                    <li role=\"presentation\" id=\"center-logo\"><p onclick=\"location.href='customerCenter.do';\">고객센터</p></li>                    \r\n");
      out.write("                    <li class=\"notice\" role=\"presentation\"><a href=\"noticeList.do\">공지사항</a></li>\r\n");
      out.write("                    <li role=\"presentation\"><a href=\"fqaList-all.do\">자주 묻는 질문</a></li>\r\n");
      out.write("                    <li role=\"presentation\"><a href=\"suggestion.do\">제안하기</a></li>\r\n");
      out.write("                    <li role=\"presentation\"><a href=\"inquireMyInfo.do\">나의 정보 조회</a></li>\r\n");
      out.write("                    <!--<li role=\"presentation\"><a href=\"#\">Frequently Asked Questions</a></li>-->\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("                <div style=\"border: 1px solid #E7EAEA; margin-top: 30px; padding: 15px;\" class=\"hidden-xs\">\r\n");
      out.write("                    <h2>제안해</h2>\r\n");
      out.write("                    <h4>경품 줄게</h4>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <h2>입점해</h2>\r\n");
      out.write("                    <p><a href=\"#\" class=\"text-secondary\">여기</a>를 클릭하세요</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-10\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <div class=\"suggestion-write-outer\">\r\n");
      out.write("                            <h3>제안사항 작성</h3><br>\r\n");
      out.write("\r\n");
      out.write("                            <form action=\"suggestionInsert.do\" method=\"post\" name=\"suggestionForm\" id=\"suggestionForm\" onsubmit=\"return validate()\" enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                \t\r\n");
      out.write("                                \t<label class=\"col-sm-1\" style=\"text-align:right;\">유형</label>\r\n");
      out.write("                                \t<div class=\"col-sm-2\">\r\n");
      out.write("                                \t\t<select class=\"form-control\" name=\"suggestionCategory\" onChange=\"showSub(this.options[this.selectedIndex].value)\">\r\n");
      out.write("                                \t\t\t<option value=\"no\" hidden>대분류 선택</option>\r\n");
      out.write("                                \t\t\t<option value=\"suggestion\">제안</option>\r\n");
      out.write("                                \t\t\t<option value=\"error\">장애/오류</option>\r\n");
      out.write("                                \t\t</select>\r\n");
      out.write("                                \t</div>\r\n");
      out.write("                                \t\r\n");
      out.write("                                \t<div class=\"col-sm-3\" id=\"suggestionDivision1\">\r\n");
      out.write("                                \t\t<select class=\"form-control\" name=\"suggestionDivision1\" style=\"display:none;\">\r\n");
      out.write("                                \t\t\t<option value=\"no\" hidden>소분류 선택</option>\r\n");
      out.write("                                \t\t\t<option value=\"sales\">상품 판매 제안</option>\r\n");
      out.write("                                \t\t\t<option value=\"event\">이벤트/혜택 제안</option>\r\n");
      out.write("                                \t\t\t<option value=\"service\">서비스 제안</option>\r\n");
      out.write("                                \t\t\t<option value=\"system\">시스템 제안</option>\r\n");
      out.write("                                \t\t\t<option value=\"compliment\">서비스 칭찬</option>\r\n");
      out.write("                                \t\t\t<option value=\"other\">기타 제안</option>\r\n");
      out.write("                                \t\t</select>\r\n");
      out.write("                                \t</div>\r\n");
      out.write("                                \t\r\n");
      out.write("                                \t<div class=\"col-sm-3\" id=\"suggestionDivision2\">\r\n");
      out.write("                                \t\t<select class=\"form-control\" name=\"suggestionDivision2\" style=\"display:none;\">\r\n");
      out.write("                                \t\t\t<option value=\"no\" hidden>소분류 선택</option>\r\n");
      out.write("                                \t\t\t<option value=\"error\">시스템 장애(PC/Mobile)</option>\r\n");
      out.write("                                \t\t\t<option value=\"mark\">표기 오류</option>\r\n");
      out.write("                                \t\t</select>\r\n");
      out.write("                                \t</div>\r\n");
      out.write("                                \t\r\n");
      out.write("                                \t<div class=\"row\"></div>\r\n");
      out.write("                                \t<br>\r\n");
      out.write("                                \t\r\n");
      out.write("                                    <label for=\"suggestion-title\" class=\"col-sm-1\" style=\"text-align:right;\">제목</label>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div class=\"col-sm-10\">\r\n");
      out.write("                                        <input type=\"text\" id=\"suggestion-title\" class=\"form-control\" name=\"suggestionTitle\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row\"></div>\r\n");
      out.write("                                    <br>\r\n");
      out.write("\r\n");
      out.write("                                    <label for=\"suggestionContents\" class=\"col-sm-1\" style=\"text-align:right;\">내용</label>\r\n");
      out.write("                                    <div class=\"col-sm-10\">\r\n");
      out.write("                                        <textarea class=\"form-control\" name=\"suggestionContents\" id=\"suggestionContents\" cols=\"30\" rows=\"15\"></textarea>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar ckeditor_config = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  resize_enaleb : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  height:450,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  enterMode : CKEDITOR.ENTER_BR,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  shiftEnterMode : CKEDITOR.ENTER_P,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  filebrowserUploadUrl : \"suggestionFilesUpload.do\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tCKEDITOR.replace(\"suggestionContents\", ckeditor_config);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div id=\"suggest_confirm_layer\" align=\"center\">\r\n");
      out.write("                                    \t<div>\r\n");
      out.write("                                    \t\t<p style=\"font-size:10px; margin-bottom:0px; color:orange;\">배송/환불/교환 접수는</p>\r\n");
      out.write("                                    \t\t<p style=\"font-size:10px; color:orange;\">마이페이지에서 가능하며</p>\r\n");
      out.write("                                    \t\t<p style=\"font-size:12px;\">상세 문의는 1:1 상담톡을 이용하시기 바랍니다.</p>\r\n");
      out.write("                                    \t</div>\r\n");
      out.write("                                    \t<div>\r\n");
      out.write("                                    \t\t<button class=\"btn btn-default\" id=\"outBtn\" type=\"button\" onclick=\"location.replace('customerCenter.do');\">나가기</button>\r\n");
      out.write("                                    \t\t<button class=\"btn btn-default\" id=\"okBtn\" type=\"button\">확인</button>\r\n");
      out.write("                                    \t</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row\"></div>\r\n");
      out.write("                                    <br>\r\n");
      out.write("\r\n");
      out.write("                                   \r\n");
      out.write("                                </div>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <p id=\"btn-group\" style=\"width:300px;margin-left:auto; margin-right:auto;\">\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-default\">등록하기</button>\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-default\" onclick=\"location.replace('customerCenter.do');\">나가기</button>\r\n");
      out.write("                                </p>\r\n");
      out.write("\r\n");
      out.write("                            </form>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$('#okBtn').on(\"click\", function(){\r\n");
      out.write("\t\t\t\t$('#suggest_confirm_layer').hide();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* function popupSuggestion(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\twindow.open(\"popupSuggestion.do\", \"a\", \"width=220, height=320, left=300, top=200\");\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction showSub(obj) {\r\n");
      out.write("\t\t\tf = document.forms.suggestionForm\r\n");
      out.write("\t\t\tsCategory = f.suggestionCategory\r\n");
      out.write("\t\t\tconsole.log(sCategory.value);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(obj == 'no'){\r\n");
      out.write("\t\t\t\tf.suggestionDivision1.style.display=\"none\";\r\n");
      out.write("\t\t\t\tf.suggestionDivision2.style.display=\"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(obj == 'suggestion') {\r\n");
      out.write("\t\t\t\tf.suggestionDivision2.style.display=\"none\";\r\n");
      out.write("\t\t\t\tf.suggestionDivision1.style.display=\"block\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(obj == 'error') {\r\n");
      out.write("\t\t\t\tf.suggestionDivision1.style.display=\"none\";\r\n");
      out.write("\t\t\t\tf.suggestionDivision2.style.display=\"block\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* function validate(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconsole.log(document.forms.suggestionForm.suggestionCategory.value);\r\n");
      out.write("\t\t\tconsole.log(document.forms.suggestionForm.suggestionDivision1.value);\r\n");
      out.write("\t\t\tconsole.log(document.forms.suggestionForm.suggestionDivision2.value);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(document.forms.suggestionForm.suggestionCategory.value == 'no'){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\talert(\"대분류를 선택해주세요^^\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else if(document.forms.suggestionForm.suggestionDivision1.value == 'no'\r\n");
      out.write("\t\t\t\t&& document.forms.suggestionForm.suggestionDivision2.value == 'no'){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\talert(\"소분류를 선택하시고 다시 등록해주세요 ^^\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
